export type User = {
  id: string;
  first_name: string;
  last_name: string;
  avatar: string;
  enrollee_id: string;
  email: string;
  gender: string;
  status: string;
  phone: string;
  dob: string;
  plan_id: string;
  band: string;
  company_name: string;
  plan: string;
  plan_type: string;
  qr_code: string;
  valid_until: string;
  state_of_origin: string;
  token: string;
};
